name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Install Node'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false
    - name: 'Install Deps'
      run: pnpm install
    - name: Run ESLint
      run: pnpm run lint
  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: 'Install Node'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false
    - name: 'Install Deps'
      run: pnpm install
    - name: 'Test'
      run: pnpm run turbo:coverage
    - name: 'Report Core Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
      with:
        json-summary-path: 'coverage/core/coverage-summary.json'
        json-final-path: 'coverage/core/coverage-final.json'
    - name: 'Report CLI Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
      with:
        json-summary-path: 'packages/cli/coverage/core/coverage-summary.json'
        json-final-path: 'packages/cli/coverage/core/coverage-final.json'
