name: Publish Package to npmjs
on:
  release:
    types: [released, prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DESIGN_REQUEST_TIMEOUT: ${{secrets.DESIGN_REQUEST_TIMEOUT}}
      WEBSOCKET_HOST: ${{secrets.WEBSOCKET_HOST}}
      API_HOST: ${{secrets.API_HOST}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - run: pnpm i
      - run: pnpm run coverage
      - run: chmod +x ./scripts/publish.sh && ./scripts/publish.sh ${{github.event.release.prerelease && '--beta' || ''}}
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
