name: Test Code Base

on:
  pull_request:

jobs:
  build:
    name: Test Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: 'Install Node'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: 'Install Deps'
      run: npm install
    - name: 'Test'
      run: npm run coverage
    - name: 'Report Coverage'
      if: always() # Also generate the report if tests are failing
      uses:  davelosert/vitest-coverage-report-action@v1
    
